name: Tests

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:      
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 3 * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.8,3.9,'3.10']
      fail-fast: false


    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install coveralls pytest-cov

    - name: install package itself
      run: |
         pip install poetry
         pip install kaleido #required on github CI by plotly
         poetry install

    - name: testing
      run: |
        poetry run pytest --cov-report term --cov=sequana_pipetools
    - name: coveralls
      run: |
        echo $COVERALLS_REPO_TOKEN
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
